<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,ref,watch} from 'vue'
import {RouterLink,useRoute} from 'vue-router'
import {session} from '../session'
import DataListControls from '../components/DataListControls.vue'
import PaginationBar from '../components/PaginationBar.vue'
import { moneyList, moneyKinds, receiptLabels, channelLabels, money, businessTime } from '../customerBusinessApi'

import type { MoneyEntry } from '../customerBusinessApi'

import '../salesBusiness.css'
const route=useRoute();const tenant=computed(()=>Number(route.params.tenantID||session.bootstrap?.actor.tenant_id||0));const seller=computed(()=>session.bootstrap?.actor.role==='sales_staff');const customer=computed(()=>session.bootstrap?.actor.role==='customer')
const items=ref<MoneyEntry[]>([]),error=ref(''),loading=ref(false),search=ref(''),status=ref('all'),kind=ref('all'),from=ref(''),to=ref(''),page=ref(1),size=ref(12),pages=ref(1),total=ref(0),view=ref<'card'|'table'>('table');let c:AbortController|undefined,timer:ReturnType<typeof setTimeout>|undefined,poll:ReturnType<typeof setInterval>|undefined
const receiptPath=computed(()=>({path:customer.value?'/finance/receipts':seller.value?'/sales/receipts':'/staff/finance/receipts',query:{tenant:tenant.value}}))
const states=Object.entries(receiptLabels).map(([value,label])=>({value,label}));states.unshift({value:'all',label:'全部交易状态'})
async function load(silent=false){if(!tenant.value){error.value='缺少客户编号';return}c?.abort();const a=new AbortController();c=a;if(!silent)loading.value=true;error.value='';try{const r=await moneyList(tenant.value,{search:search.value,status:status.value,kind:kind.value,from:from.value,to:to.value,page:page.value,page_size:size.value},a.signal);if(a.signal.aborted)return;items.value=r.items;total.value=r.total;pages.value=Math.max(1,r.total_pages);if(page.value>pages.value)page.value=pages.value}catch(e){if(!a.signal.aborted)error.value=e instanceof Error?e.message:'读取失败'}finally{if(c===a)loading.value=false}}
function first(){if(page.value!==1)page.value=1;else void load()};watch([status,kind,from,to,size,tenant],first);watch(page,()=>load());watch(search,()=>{clearTimeout(timer);timer=setTimeout(first,300)});onMounted(()=>{void load();poll=setInterval(()=>{if(!document.hidden&&!loading.value)void load(true)},15000)});onBeforeUnmount(()=>{c?.abort();clearTimeout(timer);clearInterval(poll)})
</script><template><div class="management-page sales-business"><header class="sb-toolbar"><div><h2>客户资金记录</h2></div><div class="sb-actions"><RouterLink :to="receiptPath">收款进度 / 提交资料</RouterLink><button @click="load()">刷新记录</button></div></header><section class="sb-panel"><DataListControls v-model:view-mode="view" v-model:search="search" v-model:status="status" v-model:page-size="size" :status-options="states" search-placeholder="按原单号搜索"/><div class="money-filter-row"><label class="money-filter-item"><span>交易类型</span><select v-model="kind"><option value="all">全部业务</option><option v-for="(label,key) in moneyKinds" :key="key" :value="key">{{label}}</option></select></label><label class="money-filter-item"><span>起始日期</span><input v-model="from" type="date"/></label><label class="money-filter-item"><span>结束日期</span><input v-model="to" type="date"/></label></div><p v-if="error" class="sb-error">{{error}} <button @click="load()">重试</button></p><p v-else-if="loading" class="sb-empty">读取资金记录中…</p><p v-else-if="!items.length" class="sb-empty">没有符合条件的资金记录；不会生成虚构流水。</p><div v-else-if="view==='table'" class="sb-table"><table><thead><tr><th>业务 / 原单号</th><th>金额</th><th>渠道</th><th>状态</th><th>发生 / 入账时间</th><th>说明</th></tr></thead><tbody><tr v-for="v in items" :key="v.entry_key"><td>{{moneyKinds[v.kind]||v.kind}}<small>{{v.reference_no}}</small></td><td>{{money(v.amount_cents)}}</td><td>{{channelLabels[v.channel]||v.channel}}</td><td>{{receiptLabels[v.status]||v.status}}</td><td>{{businessTime(v.occurred_at)}}<small>入账：{{businessTime(v.posted_at)}}</small></td><td>{{v.note}}</td></tr></tbody></table></div><div v-else class="sb-grid"><article v-for="v in items" :key="v.entry_key" class="sb-record"><header><h3>{{moneyKinds[v.kind]||v.kind}}</h3><span>{{money(v.amount_cents)}}</span></header><p>{{receiptLabels[v.status]||v.status}} · {{channelLabels[v.channel]||v.channel}}</p><small>{{v.reference_no}}</small><p>{{v.note}}</p><small>{{businessTime(v.occurred_at)}}；入账 {{businessTime(v.posted_at)}}</small></article></div><PaginationBar v-if="!error&&!loading" v-model:page="page" :total="total" :total-pages="pages" :page-size="size"/></section></div></template>
