<script setup lang="ts">
import {inbox} from '../workInbox'
import {computed,onBeforeUnmount,onMounted,reactive,ref,watch} from 'vue'
import {useRoute} from 'vue-router'
import {session} from '../session'
import DataListControls from '../components/DataListControls.vue'
import PaginationBar from '../components/PaginationBar.vue'
import BusinessDialog from '../components/BusinessDialog.vue'
import BusinessHistory from '../components/BusinessHistory.vue'
import CustomerAccountPicker from '../components/CustomerAccountPicker.vue'
import {ticketList,createTicket,ticketAction,ticketLabels,categoryLabels,actionLabels,businessTime} from '../customerBusinessApi'
import type {Ticket} from '../customerBusinessApi'
import '../salesBusiness.css'
const route=useRoute();const actor=computed(()=>session.bootstrap?.actor),operations=computed(()=>actor.value?.role!=='customer'&&actor.value?.role!=='sales_staff'),customer=computed(()=>actor.value?.role==='customer'),tenant=computed(()=>Number(route.query.tenant||0))
const items=ref<Ticket[]>([]),page=ref(1),size=ref(12),total=ref(0),pages=ref(1),search=ref(''),status=ref('all'),view=ref<'table'|'card'>('table'),loading=ref(false),error=ref(''),notice=ref('')
const states=Object.entries(ticketLabels).map(([value,label])=>({value,label}));states.unshift({value:'all',label:'全部工单状态'})
let c:AbortController|undefined,timer:ReturnType<typeof setTimeout>|undefined,poll:ReturnType<typeof setInterval>|undefined
const mode=ref(''),target=ref<Ticket|null>(null),saving=ref(false),formError=ref(''),action=ref('reply'),note=ref('')
const form=reactive({tenant_id:0,category:'equipment',title:'',description:'',contact_name:'',contact_phone:'',preferred_at:'',key:''})
async function load(silent=false){c?.abort();const a=new AbortController();c=a;if(!silent)loading.value=true;error.value='';try{const r=await ticketList({tenant_id:tenant.value||undefined,search:search.value,status:status.value,page:page.value,page_size:size.value},a.signal);if(a.signal.aborted)return;items.value=r.items;total.value=r.total;pages.value=Math.max(1,r.total_pages);if(page.value>pages.value)page.value=pages.value}catch(e){if(!a.signal.aborted)error.value=e instanceof Error?e.message:'读取失败'}finally{if(c===a)loading.value=false}}
function first(){if(page.value!==1)page.value=1;else void load()};watch([status,size,tenant],first);watch(page,()=>load());watch(search,()=>{clearTimeout(timer);timer=setTimeout(first,300)});onMounted(()=>{void load();window.addEventListener('work-inbox-updated',refreshOnInbox);poll=setInterval(()=>{if(customer.value||inbox.error)refreshOnInbox()},60000)});onBeforeUnmount(()=>{c?.abort();clearTimeout(timer);clearInterval(poll);window.removeEventListener('work-inbox-updated',refreshOnInbox)})
function refreshOnInbox(){if(!document.hidden&&!mode.value&&!loading.value)void load(true)}
function add(){Object.assign(form,{tenant_id:customer.value?actor.value?.tenant_id:tenant.value,category:'equipment',title:'',description:'',contact_name:customer.value?actor.value?.display_name||'':'',contact_phone:customer.value?actor.value?.phone||'':'',preferred_at:'',key:crypto.randomUUID()});mode.value='create';formError.value=''}
function actions(v:Ticket):string[]{if(operations.value){if(v.status==='pending')return ['accept'];if(v.status==='accepted')return ['start','wait_customer','reply'];if(v.status==='in_progress')return ['reply','wait_customer','resolve'];if(v.status==='waiting_customer')return ['reply','resolve'];if(v.status==='awaiting_confirmation')return ['reply'];return []}if(v.status==='awaiting_confirmation')return ['confirm','reopen','reply'];if(v.status==='completed')return ['reopen'];if(['pending','accepted','waiting_customer'].includes(v.status))return ['reply','cancel'];if(v.status==='in_progress')return ['reply'];return []}
function open(v:Ticket,m:string,a='reply'){target.value=v;mode.value=m;action.value=a;note.value='';formError.value=''}
async function save(){if(saving.value)return;saving.value=true;formError.value='';try{if(mode.value==='create')await createTicket({tenant_id:form.tenant_id,category:form.category,title:form.title,description:form.description,contact_name:form.contact_name,contact_phone:form.contact_phone,preferred_at:form.preferred_at?new Date(form.preferred_at).toISOString():undefined,idempotency_key:form.key});else if(target.value)await ticketAction(target.value,action.value,note.value);notice.value=mode.value==='create'?'协助申请已提交，等待运维受理；没有自动授予任何代操作权限。':'工单进度已更新。';mode.value='';await load()}catch(e){formError.value=e instanceof Error?e.message:'处理失败';await load(true)}finally{saving.value=false}}
</script>
<template><div class="management-page sales-business"><header class="sb-toolbar"><div><h2>{{operations?'运维协助工单':'申请运维协助'}}</h2><p>{{operations?'受理销售代申请与客户自助申请，记录处理结果，再由申请方确认。':'客户需要协助时提交工单，查看处理人、进度、回复和处理结果。'}}</p></div><div class="sb-actions"><button @click="load()">刷新工单</button><button v-if="!operations" class="primary" @click="add">新建协助申请</button></div></header><p class="sb-note">申请不等于授权。修改用户层、主播训练和声音复刻仍须客户单独授权给具体运维人员；未授权不得操作。没有直播间也可提交安装或开户咨询。</p><p v-if="notice" class="sb-success" role="status">{{notice}}</p><section class="sb-panel"><DataListControls v-model:view-mode="view" v-model:search="search" v-model:status="status" v-model:page-size="size" :status-options="states" search-placeholder="工单号、问题或客户名称"/><p v-if="error" class="sb-error">{{error}} <button @click="load()">重试</button></p><p v-else-if="loading" class="sb-empty">读取工单中…</p><p v-else-if="!items.length" class="sb-empty">暂无符合条件的协助工单。</p><div v-else-if="view==='table'" class="sb-table"><table><thead><tr><th>问题 / 客户</th><th>来源 / 类别</th><th>状态 / 处理人</th><th>预约 / 更新时间</th><th>操作</th></tr></thead><tbody><tr v-for="v in items" :key="v.id"><td><strong>{{v.title}}</strong><small>{{v.customer_name}} · {{v.ticket_no}}</small></td><td>{{v.requester_role==='sales_staff'?'销售代申请':'客户自助申请'}}<small>{{categoryLabels[v.category]}}</small></td><td><span class="sb-badge">{{ticketLabels[v.status]}}</span><small>{{v.assigned_name||'尚未接单'}}</small></td><td>{{businessTime(v.preferred_at)}}<small>更新：{{businessTime(v.updated_at)}}</small></td><td><div class="sb-actions"><button @click="open(v,'detail')">详情与历史</button><button v-for="a in actions(v)" :key="a" @click="open(v,'action',a)">{{actionLabels[a]}}</button></div></td></tr></tbody></table></div><div v-else class="sb-grid"><article v-for="v in items" :key="v.id" class="sb-record"><header><h3>{{v.title}}</h3><span class="sb-badge">{{ticketLabels[v.status]}}</span></header><p>{{v.customer_name}} · {{categoryLabels[v.category]}}</p><p>{{v.description}}</p><small>{{v.assigned_name||'尚未接单'}} · {{businessTime(v.updated_at)}}</small><div class="sb-actions"><button @click="open(v,'detail')">详情与历史</button><button v-for="a in actions(v)" :key="a" @click="open(v,'action',a)">{{actionLabels[a]}}</button></div></article></div><PaginationBar v-if="!loading&&!error" v-model:page="page" :total="total" :total-pages="pages" :page-size="size"/></section>
<BusinessDialog v-if="mode" :title="mode==='create'?'新建协助申请':mode==='action'?actionLabels[action]:'工单详情'" :busy="saving" @close="mode=''"><p v-if="formError" class="sb-error" role="alert">{{formError}}</p><form v-if="mode==='create'" class="sb-form" @submit.prevent="save"><CustomerAccountPicker v-if="!customer&&!tenant" v-model="form.tenant_id" class="sb-wide"/><p v-else class="sb-wide">客户 #{{form.tenant_id}}</p><label>协助类别<select v-model="form.category"><option v-for="(label,key) in categoryLabels" :key="key" :value="key">{{label}}</option></select></label><label>问题标题<input v-model="form.title" maxlength="160" required/></label><label class="sb-wide">问题描述<textarea v-model="form.description" maxlength="2000" required placeholder="设备、现象、希望协助的内容；请勿填写密码"/></label><label>客户联系人<input v-model="form.contact_name" maxlength="128" required/></label><label>联系电话<input v-model="form.contact_phone" maxlength="64" inputmode="tel" required/></label><label>希望联系时间<input v-model="form.preferred_at" type="datetime-local"/></label><p class="sb-note sb-wide">本次只申请协助，不授予账号、用户层、训练或声音复刻权限。</p><button class="primary sb-wide" :disabled="saving||!form.tenant_id">{{saving?'提交中…':'提交协助申请'}}</button></form><template v-else-if="target"><h3>{{target.title}}</h3><p>{{target.customer_name}} · {{target.ticket_no}}</p><p class="sb-note">{{target.description}}</p><p>联系 {{target.contact_name}} · {{target.contact_phone}}；预约 {{businessTime(target.preferred_at)}}</p><p>处理人 {{target.assigned_name||'尚未接单'}}；状态 {{ticketLabels[target.status]}}</p><p v-if="target.resolution">处理结果：{{target.resolution}}</p><form v-if="mode==='action'" class="sb-form" @submit.prevent="save"><label class="sb-wide">{{action==='resolve'?'处理结果（提交后待客户确认）':action==='confirm'?'确认说明':'补充 / 处理说明'}}<textarea v-model="note" required maxlength="2000"/></label><button class="primary sb-wide" :disabled="saving">{{saving?'处理中…':actionLabels[action]}}</button></form><BusinessHistory v-else kind="ticket" :id="target.id"/></template></BusinessDialog></div></template>
