<script lang="ts">
 import {onMount,onDestroy} from 'svelte';import {session} from '$lib/session';
 export let mode:'customer'|'sales'='customer';
 interface Ticket{id:number;tenant_id:number;title:string;description:string;ticket_no:string;customer_name:string;status:string;assigned_name:string;resolution:string;version:number;updated_at:string}
 interface Account{tenant_id:number;name:string;username:string}
 interface EventItem{id:number;actor_name:string;action:string;note:string;created_at:string}
 const labels:Record<string,string>={pending:'待受理',accepted:'已接单',in_progress:'处理中',waiting_customer:'待客户反馈',awaiting_confirmation:'待确认完成',completed:'已完成',cancelled:'已取消'};
 const categories:Record<string,string>={onboarding:'开户 / 安装咨询',equipment:'设备问题',live_config:'直播配置',policy:'策略协助',training:'主播训练',voice:'声音协助',other:'其他'};
 const actions:Record<string,string>={reply:'补充回复',confirm:'确认已解决',cancel:'取消申请',reopen:'未解决 / 重新打开'};
 let tickets:Ticket[]=[],selected:Ticket|null=null,events:EventItem[]=[],accounts:Account[]=[];
 let page=1,size=12,pages=1,total=0,search='',status='all',view='card',loading=false,error='',notice='',creating=false,saving=false;
 let accountSearch='',accountPage=1,accountPages=1,historyPage=1,historyPages=1,action='reply',note='';
 let form={tenant_id:0,category:'equipment',title:'',description:'',contact_name:'',contact_phone:'',preferred_at:'',idempotency_key:''};
 let current:AbortController|undefined,poll:ReturnType<typeof setInterval>|undefined;let stopped=false;
 async function api<T>(url:string,method='GET',body?:unknown,signal?:AbortSignal):Promise<T>{const r=await fetch(url,{method,credentials:'include',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal:signal||AbortSignal.timeout(15000)});const data=await r.json().catch(()=>({error:'返回内容异常'}));if(!r.ok)throw new Error(data.error||'请求失败');return data as T}
 function qs(v:Record<string,string|number>){return '?'+new URLSearchParams(Object.entries(v).map(([k,v])=>[k,String(v)]))}
 async function load(){current?.abort();const c=new AbortController();current=c;loading=true;error='';try{const r=await api<{items:Ticket[];total:number;total_pages:number}>('/api/v1/service/tickets'+qs({page,page_size:size,search,status}),'GET',undefined,c.signal);if(!c.signal.aborted&&!stopped){tickets=r.items;total=r.total;pages=Math.max(1,r.total_pages);if(page>pages){page=pages;void load()}}}catch(e){if(!c.signal.aborted)error=e instanceof Error?e.message:'读取失败'}finally{if(current===c)loading=false}}
 async function loadAccounts(){try{const r=await api<{items:Account[];total_pages:number}>('/api/v1/customer-business/accounts'+qs({search:accountSearch,page:accountPage,page_size:12}));accounts=r.items;accountPages=Math.max(1,r.total_pages)}catch(e){error=e instanceof Error?e.message:'读取客户失败'}}
 async function add(){error='';form={tenant_id:mode==='customer'?Number($session.bootstrap?.actor.tenant_id):Number(new URLSearchParams(location.search).get('tenant')||0),category:'equipment',title:'',description:'',contact_name:mode==='customer'?$session.bootstrap?.actor.display_name||'':'',contact_phone:'',preferred_at:'',idempotency_key:crypto.randomUUID()};creating=true;selected=null;if(mode==='sales')await loadAccounts()}
 async function submit(){if(saving)return;saving=true;error='';try{await api('/api/v1/service/tickets','POST',{...form,preferred_at:form.preferred_at?new Date(form.preferred_at).toISOString():undefined});creating=false;notice='申请已提交，等待运维受理。没有自动授予代操作权限。';await load()}catch(e){error=e instanceof Error?e.message:'提交失败'}finally{saving=false}}
 async function history(){if(!selected)return;try{const r=await api<{items:EventItem[];total_pages:number}>('/api/v1/service/tickets/'+selected.id+'/events'+qs({page:historyPage,page_size:12}));events=r.items;historyPages=Math.max(1,r.total_pages)}catch(e){error=e instanceof Error?e.message:'读取历史失败'}}
 async function detail(t:Ticket){selected=t;creating=false;historyPage=1;note='';action=choices(t)[0]||'reply';await history()}
 function choices(t:Ticket):string[]{if(t.status==='awaiting_confirmation')return ['confirm','reopen','reply'];if(t.status==='completed')return ['reopen'];if(['pending','accepted','waiting_customer'].includes(t.status))return ['reply','cancel'];if(t.status==='in_progress')return ['reply'];return []}
 async function update(){if(!selected||saving)return;saving=true;error='';try{selected=await api<Ticket>('/api/v1/service/tickets/'+selected.id+'/actions','POST',{action,note,version:selected.version});action=choices(selected)[0]||'reply';note='';notice='处理进度已更新';await history();await load()}catch(e){error=e instanceof Error?e.message:'保存失败'}finally{saving=false}}
 function filter(){page=1;void load()}
 onMount(()=>{void load();poll=setInterval(()=>{if(!document.hidden&&!selected&&!creating&&!loading)void load()},15000)});onDestroy(()=>{stopped=true;current?.abort();clearInterval(poll)})
</script>
<section class="support-page"><header><h1>运维协助</h1><a href="/me">返回我的</a></header><p>销售代申请与客户自助申请进入同一工单；接单、处理结果和完成确认可追踪。</p><p class="note">申请不是授权。L3、主播训练和声音复刻须客户另行授权；没有直播间也能申请安装咨询。</p>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if notice}<p class="notice" role="status">{notice}</p>{/if}
 {#if creating}<form on:submit|preventDefault={submit}><h2>新建协助申请</h2>{#if mode==='sales'}<div class="picker"><label>选择本人客户<input bind:value={accountSearch} placeholder="客户名称或账号"/></label><button type="button" on:click={()=>{accountPage=1;loadAccounts()}}>搜索客户</button><div class="row">{#each accounts as a}<button class:active={form.tenant_id===a.tenant_id} type="button" on:click={()=>form.tenant_id=a.tenant_id}>{a.name} · @{a.username}</button>{/each}</div><div class="row"><button disabled={accountPage<=1} type="button" on:click={()=>{accountPage--;loadAccounts()}}>上一页客户</button><span>{accountPage}/{accountPages}</span><button disabled={accountPage>=accountPages} type="button" on:click={()=>{accountPage++;loadAccounts()}}>下一页客户</button></div><small>已选择客户 #{form.tenant_id||'未选择'}</small></div>{/if}<label>协助类别<select bind:value={form.category}>{#each Object.entries(categories) as [key,label]}<option value={key}>{label}</option>{/each}</select></label><label>问题标题<input bind:value={form.title} required maxlength="160"/></label><label>问题描述<textarea bind:value={form.description} required maxlength="2000" rows="4" placeholder="描述问题，不填写密码"></textarea></label><label>联系人<input bind:value={form.contact_name} required maxlength="128"/></label><label>联系电话<input bind:value={form.contact_phone} required inputmode="tel" maxlength="64"/></label><label>期望联系时间<input bind:value={form.preferred_at} type="datetime-local"/></label><div class="row"><button class="primary" type="submit" disabled={saving||!form.tenant_id}>{saving?'提交中…':'提交协助申请'}</button><button type="button" disabled={saving} on:click={()=>creating=false}>取消</button></div></form>
 {:else if selected}<article><h2>{selected.title}</h2><p>{selected.customer_name} · {selected.ticket_no}</p><p class="badge">{labels[selected.status]} · {selected.assigned_name||'尚未接单'}</p><p>{selected.description}</p>{#if selected.resolution}<p class="note">处理结果：{selected.resolution}</p>{/if}{#if choices(selected).length}<form on:submit|preventDefault={update}><label>操作<select bind:value={action}>{#each choices(selected) as key}<option value={key}>{actions[key]}</option>{/each}</select></label><label>补充 / 确认说明<textarea bind:value={note} required maxlength="2000" rows="3"></textarea></label><button class="primary" disabled={saving}>{saving?'保存中…':'提交处理'}</button></form>{/if}<h3>处理历史</h3>{#each events as e}<article class="history"><strong>{e.actor_name}</strong><p>{e.note}</p><small>{new Date(e.created_at).toLocaleString('zh-CN',{hour12:false})}</small></article>{/each}<div class="row"><button disabled={historyPage<=1} on:click={()=>{historyPage--;history()}}>上一页历史</button><span>{historyPage}/{historyPages}</span><button disabled={historyPage>=historyPages} on:click={()=>{historyPage++;history()}}>下一页历史</button></div><button on:click={()=>selected=null}>返回工单列表</button></article>
 {:else}<div class="row"><button class="primary" on:click={add}>新建协助申请</button><button on:click={load}>刷新</button><button class:active={view==='card'} on:click={()=>view='card'}>卡片</button><button class:active={view==='table'} on:click={()=>view='table'}>表格</button></div><form on:submit|preventDefault={filter}><label>搜索<input bind:value={search} placeholder="工单号 / 问题 / 客户"/></label><label>状态<select bind:value={status} on:change={filter}><option value="all">全部状态</option>{#each Object.entries(labels) as [key,label]}<option value={key}>{label}</option>{/each}</select></label><label>每页<select bind:value={size} on:change={filter}><option value={12}>12</option><option value={24}>24</option><option value={48}>48</option></select></label><button>搜索</button></form>{#if loading}<p role="status">读取中…</p>{:else if !tickets.length}<p class="note">暂无符合条件的工单。</p>{:else if view==='card'}{#each tickets as t}<article><header><h2>{t.title}</h2><span class="badge">{labels[t.status]}</span></header><p>{t.customer_name}</p><p>{t.description}</p><small>{t.assigned_name||'待接单'}</small><button on:click={()=>detail(t)}>详情 / 回复 / 确认</button></article>{/each}{:else}<div class="table"><table><thead><tr><th>问题 / 客户</th><th>状态</th><th>处理人</th><th>操作</th></tr></thead><tbody>{#each tickets as t}<tr><td>{t.title}<small>{t.customer_name}</small></td><td>{labels[t.status]}</td><td>{t.assigned_name||'待接单'}</td><td><button on:click={()=>detail(t)}>详情</button></td></tr>{/each}</tbody></table></div>{/if}<div class="row"><button disabled={loading||page<=1} on:click={()=>{page--;load()}}>上一页</button><span>{page}/{pages} · 共 {total} 条</span><button disabled={loading||page>=pages} on:click={()=>{page++;load()}}>下一页</button></div>{/if}
</section>
<style>.support-page{font-size:16px;line-height:1.6;padding:20px 16px 110px;color:#273d5d}.support-page h1{font-size:26px}.support-page h2{font-size:19px}.support-page h3{font-size:18px}.support-page header,.support-page .row{display:flex;gap:10px;flex-wrap:wrap;align-items:center;justify-content:space-between}.support-page button,.support-page input,.support-page textarea,.support-page select{font:inherit;font-size:16px;min-height:44px;border:1px solid #c6d9f9;background:#fcfdff;border-radius:10px;padding:9px 12px;color:inherit}.support-page button{cursor:pointer}.support-page button:hover,.support-page button:focus-visible,.support-page article:hover{border-color:#6b9fe9;box-shadow:0 0 0 3px #3c84eb18,0 5px 16px #3271ce22}.support-page .primary,.support-page .active{background:#346ed5;color:#fff}.support-page button:disabled{opacity:.45;cursor:not-allowed}.support-page form,.support-page label{display:grid;gap:8px}.support-page form{gap:14px;margin:14px 0}.support-page input,.support-page textarea,.support-page select{width:100%;box-sizing:border-box}.support-page article{border:1px solid #d9e6f9;border-radius:16px;background:linear-gradient(145deg,#f5f9ff,#fff);padding:17px;margin:14px 0}.support-page article p{white-space:pre-wrap;overflow-wrap:anywhere}.support-page small{display:block;font-size:14px;color:#6b7d96}.support-page .note{background:#eef5ff;padding:12px;border-radius:10px}.support-page .error{background:#fff1f1;color:#963b3b;padding:12px;border-radius:10px}.support-page .notice{background:#ecf9f0;color:#287450;padding:12px;border-radius:10px}.support-page .badge{background:#eaf2ff;color:#3665ac;border-radius:9px;padding:4px 8px}.support-page .table{overflow-x:auto}.support-page table{min-width:580px;width:100%;border-collapse:collapse}.support-page th,.support-page td{font-size:16px;padding:12px;border-bottom:1px solid #dfe8f7;text-align:left}.support-page th{background:#eef4ff}.support-page tr:hover td{background:#eff6ff}.support-page .history{background:white}</style>
