CREATE TABLE IF NOT EXISTS device_business_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    device_id BIGINT UNSIGNED NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    room_id BIGINT UNSIGNED NULL,
    request_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    business_type VARCHAR(48) NOT NULL,
    payload_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'processing',
    action VARCHAR(32) NOT NULL DEFAULT '',
    operation VARCHAR(32) NOT NULL DEFAULT '',
    transcript TEXT NOT NULL,
    question VARCHAR(512) NOT NULL DEFAULT '',
    value_json JSON NULL,
    message VARCHAR(512) NOT NULL DEFAULT '',
    result_text TEXT NOT NULL,
    asset_id BIGINT UNSIGNED NULL,
    billing_mode VARCHAR(16) NOT NULL DEFAULT 'disabled',
    charged_beans BIGINT NOT NULL DEFAULT 0,
    expires_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_device_business_request (device_id,tenant_id,request_id,business_type),
    KEY idx_device_business_queue (business_type,status,id),
    KEY idx_device_business_customer (tenant_id,device_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
