package db

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"livecompanion/management/internal/model"
)

func auditRefreshTx(ctx context.Context, tx *sql.Tx, job model.LiveContentRefreshJob, action string, payload any, now time.Time) error {
	raw, err := json.Marshal(payload)
	if err != nil {
		return err
	}
	_, err = tx.ExecContext(ctx, `INSERT INTO live_content_refresh_events(job_id,tenant_id,room_id,action,payload_json,created_at) VALUES(?,?,?,?,?,?)`, job.ID, job.TenantID, job.RoomID, action, string(raw), now)
	return err
}

// Cancellation is a durable outbox. A restart must still revoke pending Core
// updates and inspect the paid assets generated by an abandoned attempt.
func (s *Store) ClaimCancelledLiveContentRefreshJob(ctx context.Context, owner, realm string, now time.Time, lease time.Duration) (model.LiveContentRefreshJob, bool, error) {
	if strings.TrimSpace(owner) == "" || lease < time.Second {
		return model.LiveContentRefreshJob{}, false, fmt.Errorf("refresh cleanup lease owner/duration required")
	}
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return model.LiveContentRefreshJob{}, false, err
	}
	defer tx.Rollback()
	j, err := scanRefreshJob(tx.QueryRowContext(ctx, contentRefreshSelect+` WHERE execution_realm=? AND status='cancelled' AND cleanup_completed_at IS NULL AND next_attempt_at<=? AND (lease_until IS NULL OR lease_until<=?) ORDER BY next_attempt_at,id LIMIT 1 FOR UPDATE SKIP LOCKED`, model.NormalizeExecutionRealm(realm), now, now))
	if errors.Is(err, sql.ErrNoRows) {
		return j, false, nil
	}
	if err != nil {
		return j, false, err
	}
	var token [24]byte
	if _, err = rand.Read(token[:]); err != nil {
		return j, false, err
	}
	j.LeaseToken = hex.EncodeToString(token[:])
	until := now.Add(lease)
	j.LeaseUntil = &until
	if _, err = tx.ExecContext(ctx, `UPDATE live_content_refresh_jobs SET lease_owner=?,lease_token=?,lease_until=?,updated_at=? WHERE id=?`, owner, j.LeaseToken, until, now, j.ID); err != nil {
		return j, false, err
	}
	if err = tx.Commit(); err != nil {
		return j, false, err
	}
	return j, true, nil
}

func (s *Store) DeferCancelledLiveContentRefreshJob(ctx context.Context, job model.LiveContentRefreshJob, now time.Time, delay time.Duration) error {
	if delay < time.Second {
		delay = time.Second
	}
	result, err := s.db.ExecContext(ctx, `UPDATE live_content_refresh_jobs SET next_attempt_at=?,lease_token='',lease_owner='',lease_until=NULL,updated_at=? WHERE id=? AND status='cancelled' AND cleanup_completed_at IS NULL AND lease_token=? AND lease_until>?`, now.Add(delay), now, job.ID, job.LeaseToken, now)
	if err != nil {
		return err
	}
	n, err := result.RowsAffected()
	if err == nil && n == 0 {
		return ErrLiveContentRefreshLeaseLost
	}
	return err
}

// Acknowledge only after Core has confirmed cancellation (or no matching update
// exists). Prepared versions were never published; discard only that prepared
// lifecycle and never overwrite a manual publish, selection or room deletion.
func (s *Store) AcknowledgeLiveContentRefreshCancellation(ctx context.Context, job model.LiveContentRefreshJob, now time.Time) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if err = lockUsableRoomTx(ctx, tx, job.TenantID, job.RoomID); err != nil {
		if !errors.Is(err, sql.ErrNoRows) && !strings.Contains(err.Error(), "永久删除") {
			return err
		}
	}
	j, err := scanRefreshJob(tx.QueryRowContext(ctx, contentRefreshSelect+` WHERE id=? FOR UPDATE`, job.ID))
	if err != nil {
		return err
	}
	if j.Status != "cancelled" || j.LeaseToken == "" || j.LeaseToken != job.LeaseToken || j.LeaseUntil == nil || !j.LeaseUntil.After(now) || j.TenantID != job.TenantID || j.RoomID != job.RoomID {
		return ErrLiveContentRefreshLeaseLost
	}
	if _, err = tx.ExecContext(ctx, `UPDATE live_agent_plan_versions SET lifecycle_status='abandoned' WHERE id=? AND tenant_id=? AND room_id=? AND plan_id=? AND lifecycle_status='prepared'`, j.ResultVersionID, j.TenantID, j.RoomID, j.PlanID); err != nil {
		return err
	}
	if err = auditRefreshTx(ctx, tx, j, "cancelled_cleanup_completed", map[string]any{"base_version_id": j.BaseVersionID, "result_version_id": j.ResultVersionID, "generated_assets": j.GeneratedAssets}, now); err != nil {
		return err
	}
	_, err = tx.ExecContext(ctx, `UPDATE live_content_refresh_jobs SET cleanup_completed_at=?,lease_token='',lease_owner='',lease_until=NULL,updated_at=? WHERE id=?`, now, now, j.ID)
	if err != nil {
		return err
	}
	return tx.Commit()
}
