<script setup lang="ts">
import {computed,reactive,ref} from 'vue'
import {session} from '../session'
import {submitReceipt,parseMoney,purposeLabels} from '../customerBusinessApi'
import CustomerAccountPicker from './CustomerAccountPicker.vue'
const props=defineProps<{tenantId?:number}>();const emit=defineEmits<{saved:[];cancel:[]}>()
const customer=computed(()=>session.bootstrap?.actor.role==='customer')
const form=reactive({tenant_id:customer.value?Number(session.bootstrap?.actor.tenant_id):props.tenantId||0,channel:'bank_transfer',purpose:'recharge',amount:'',reference:'',payer_name:'',receiving_account:'',external_trade_no:'',evidence:'',occurred_at:'',key:crypto.randomUUID()})
const saving=ref(false),error=ref(''),confirmed=ref(false)
async function save(){if(!confirmed.value||saving.value)return;error.value='';saving.value=true;try{const refid=form.reference?Number(form.reference):undefined;if(refid!==undefined&&(!Number.isSafeInteger(refid)||refid<=0))throw new Error('关联单据编号无效');await submitReceipt({tenant_id:form.tenant_id,channel:form.channel,purpose:form.purpose,amount_cents:parseMoney(form.amount),order_id:form.purpose==='order'?refid:undefined,verified_payment_id:form.purpose==='platform_payment'?refid:undefined,existing_recharge_id:form.purpose==='existing_recharge'?refid:undefined,payer_name:form.payer_name,receiving_account:form.receiving_account,external_trade_no:form.external_trade_no,evidence:form.evidence,occurred_at:new Date(form.occurred_at).toISOString(),idempotency_key:form.key});emit('saved')}catch(e){error.value=e instanceof Error?e.message:'提交失败'}finally{saving.value=false}}
</script><template><form class="sb-form" @submit.prevent="save"><h2 class="sb-wide">提交收款资料</h2><p class="sb-note sb-wide">提交不等于入账。财务核实实际到账、审核并成功入账后才认定真实客户。不得提交赠送、模拟支付或内部调整；已充值过的款请选“关联既有充值”，不要再次入账。</p><p v-if="error" class="sb-error sb-wide" role="alert">{{error}}</p><CustomerAccountPicker v-if="!customer&&!props.tenantId" v-model="form.tenant_id" class="sb-wide"/><p v-else class="sb-wide">客户 #{{form.tenant_id}}</p><label>收款来源<select v-model="form.channel" @change="form.purpose=form.channel==='platform'?'platform_payment':'recharge'"><option value="bank_transfer">转账</option><option value="offline">线下收款</option><option value="platform">平台支付</option></select></label><label>款项用途<select v-model="form.purpose"><template v-for="(label,value) in purposeLabels" :key="value"><option v-if="(form.channel==='platform')===(value==='platform_payment')" :value="value">{{label}}</option></template></select></label><label>实收金额（元）<input v-model="form.amount" inputmode="decimal" required placeholder="0.00"/></label><label>实际收款时间<input v-model="form.occurred_at" type="datetime-local" required/></label><label v-if="form.purpose!=='recharge'">{{form.purpose==='order'?'订单ID':form.purpose==='platform_payment'?'服务端支付记录ID':'原充值单ID'}}<input v-model="form.reference" type="number" min="1" required/></label><label>付款方<input v-model="form.payer_name" maxlength="128" required/></label><label>收款账户标识<input v-model="form.receiving_account" maxlength="128" required placeholder="公司收款账户或门店收银账户标识"/></label><label>银行 / 渠道流水号或线下收据号<input v-model="form.external_trade_no" maxlength="128" required/></label><label class="sb-wide">凭据编号与材料说明<textarea v-model="form.evidence" maxlength="2000" required placeholder="填写可供财务核验的凭据编号、付款方、订单和到账说明；不接受仅口头成交"/></label><p v-if="form.channel==='platform'" class="sb-note sb-wide">仅接受服务端已有的真实支付宝 / 微信支付记录。当前模拟支付不能通过，尚未接入真实渠道时不能用此选项模拟入账。</p><label class="sb-wide"><span><input v-model="confirmed" type="checkbox" required style="width:auto"/> 确认提交真实收款资料，由财务独立核验；我没有把同一笔钱重复提交。</span></label><div class="sb-actions sb-wide"><button class="primary" type="submit" :disabled="saving||!confirmed">{{saving?'提交中…':'提交财务审核'}}</button><button type="button" :disabled="saving" @click="emit('cancel')">取消</button></div></form></template>
